import React, { useEffect, useState } from 'react'
import { Icon } from '../Icon.jsx'
import { Avatar, Logo } from '../common.jsx'
import { actionVisible } from '../../lib/advanced-filters.js'
import { enabledPages, t } from '../../lib/workspace.js'

export function Sidebar({ page, setPage, user, settings, onLogout, mobileOpen, onClose }) {
  const pageLabels = { overview: 'Overview', projects: 'Projects', tasks: 'My work', people: 'People', activity: 'Activity', reports: 'Reports', alerts: 'Alerts', settings: 'Settings' }
  const pages = [['overview','Overview'],['projects','Projects'],['tasks','My work'],['people','People'],['activity','Activity'],['reports','Reports'],['alerts','Alerts'],['settings','Settings']].filter(([id]) => id === 'settings' ? user?.role === 'Administrator' : enabledPages(settings).includes(id))
  return <aside className={`sidebar ${mobileOpen ? 'mobile-open' : ''}`}><div className="brand"><Logo/><span>{settings.workspace?.applicationName || 'atlas'}</span><span className="brand-beta">workspace</span><button className="icon-button mobile-close" onClick={onClose}><Icon name="close" size={15}/></button></div><div className="workspace-switcher"><div className="workspace-logo">{(settings.workspaceName || 'A')[0]}</div><div><strong>{settings.workspaceName}</strong><small>{settings.workspaceUnit}</small></div><Icon name="down" size={14}/></div><div className="sidebar-section-label">Workspace</div><nav className="nav-list">{pages.map(([id, label]) => <button key={id} className={`nav-item ${page === id ? 'active' : ''}`} onClick={() => { setPage(id); onClose?.() }}><Icon name={id === 'settings' ? 'settings' : id} size={18}/><span>{t(settings, `nav.${id}`, pageLabels[id] || label)}</span>{id === 'tasks' && <span className="nav-count">{user?.openTasks || 0}</span>}{id === 'alerts' && user?.openAlerts > 0 && <span className="alert-dot"/>}</button>)}</nav><div className="sidebar-spacer"/><div className="profile-row"><Avatar name={user?.name} color={user?.avatarColor}/><div><strong>{user?.name}</strong><small>{user?.role}</small></div><button className="logout-button" onClick={onLogout}><Icon name="logout" size={15}/></button></div></aside>
}
export function Topbar({ page, user, setPage, onCreate, onSearch, onToggleTheme, onOpenNav, canCreate = true, settings }) { const titles = { overview: ['Overview', 'Key metrics and attention items.'], projects: ['Projects', 'Health, owners, milestones.'], tasks: ['My work', 'Manage workflow state.'], people: ['People', 'Teams and capacity.'], activity: ['Activity', 'Updates and blockers.'], reports: ['Reports', 'Trends, evidence, exports.'], alerts: ['Alerts', 'Risks and deadlines.'], settings: ['Settings', 'Workspace administration.'] }; const [rawTitle, subtitle] = titles[page] || titles.overview; const title = t(settings, `nav.${page}`, rawTitle); return <header className="topbar"><div className="mobile-brand"><Logo/><span>atlas</span></div><div className="page-heading"><h1>{title}</h1><p>{subtitle}</p></div><div className="top-actions"><button className="search-box" onClick={onSearch}><Icon name="search" size={16}/><span>{t(settings, 'actions.search', 'Search anything')}</span><kbd>⌘K</kbd></button><button className="icon-button" onClick={onToggleTheme} aria-label="Toggle theme"><Icon name="moon" size={18}/></button>{enabledPages(settings).includes('alerts') && <button className="notification-button" onClick={() => setPage('alerts')}><Icon name="alerts" size={18}/>{user?.openAlerts > 0 && <span/>}</button>}{page !== 'settings' && canCreate && <button className="primary-button top-add" onClick={onCreate}><Icon name="plus" size={16}/><span>{t(settings, 'actions.new', 'New')}</span></button>}<button className="mobile-menu" onClick={onOpenNav}><Icon name="menu"/></button></div></header> }
export function CommandSearch({ open, onClose, data, setPage, openModal, settings, canEditTasks = false, canEditProjects = false, canEditPeople = false, isAdministrator = false }) {
  const [query, setQuery] = useState('')
  useEffect(() => { if (!open) setQuery('') }, [open])
  if (!open) return null
  const q = query.toLowerCase()
  const visiblePages = new Set(enabledPages(settings))
  const pages = [['overview','Overview'],['projects','Projects'],['tasks','My work'],['people','People'],['activity','Activity'],['reports','Reports'],['alerts','Alerts'],['settings','Settings']].filter(([id, label]) => (id === 'settings' ? isAdministrator : visiblePages.has(id)) && label.toLowerCase().includes(q))
  const tasks = data.tasks.filter(task => `${task.title} ${task.project} ${task.id}`.toLowerCase().includes(q)).slice(0, 6)
  const projects = data.projects.filter(project => `${project.name} ${project.code}`.toLowerCase().includes(q)).slice(0, 6)
  const people = data.people.filter(person => `${person.name} ${person.email}`.toLowerCase().includes(q)).slice(0, 6)
  const go = (page, fn) => { setPage(page); fn?.(); onClose() }
  return <div className="command-backdrop" onMouseDown={event => event.target === event.currentTarget && onClose()}><div className="command-panel"><div className="command-input"><Icon name="search" size={17}/><input autoFocus value={query} onChange={event => setQuery(event.target.value)} placeholder="Search pages, tasks, people, projects…"/><kbd>Esc</kbd></div><div className="command-sections"><section><h4>Pages</h4>{pages.map(([id, label]) => <button key={id} onClick={() => go(id)}><Icon name={id === 'settings' ? 'settings' : id} size={15}/><span>{label}</span></button>)}</section>{projects.length > 0 && <section><h4>Projects</h4>{projects.map(project => <button key={project.numericId} onClick={() => go('projects', canEditProjects && actionVisible(settings, 'edit') ? () => openModal('project', project) : undefined)}><Icon name="projects" size={15}/><span>{project.name}</span><small>{project.code}</small></button>)}</section>}{tasks.length > 0 && <section><h4>Tasks</h4>{tasks.map(task => <button key={task.numericId} onClick={() => go('tasks', canEditTasks && actionVisible(settings, 'edit') ? () => openModal('task', task) : undefined)}><Icon name="tasks" size={15}/><span>{task.title}</span><small>{task.id}</small></button>)}</section>}{people.length > 0 && <section><h4>People</h4>{people.map(person => <button key={person.id} onClick={() => go('people', canEditPeople && actionVisible(settings, 'edit') ? () => openModal('person', person) : undefined)}><Icon name="people" size={15}/><span>{person.name}</span><small>{person.team}</small></button>)}</section>}</div></div></div>
}
export function QuickActionRail({ openModal, setPage, canManage, canCreateTasks = false, canLogActivity = true, settings, onSearch }) {
  const actions = []
  if (canCreateTasks) actions.push(['New task','tasks',() => openModal('task')])
  if (canManage && actionVisible(settings, 'create')) actions.push(['New project','projects',() => openModal('project')])
  if (canLogActivity && actionVisible(settings, 'create')) actions.push(['Log update','activity',() => openModal('activity')])
  if (enabledPages(settings).includes('reports')) actions.push(['Reports','reports',() => setPage('reports')])
  if (enabledPages(settings).includes('alerts')) actions.push(['Alerts','alerts',() => setPage('alerts')])
  actions.push(['Search','search',onSearch])
  return <div className="quick-action-rail">{actions.map(([label, icon, run]) => <button key={label} onClick={run}><Icon name={icon} size={14}/>{label}</button>)}</div>
}
