import React, { useEffect, useState } from 'react'
import { Icon } from '../Icon.jsx'
import { actionVisible } from '../../lib/advanced-filters.js'
import { workflowStateLabels } from '../../lib/workflows.js'
import { customFieldDefinitions, hasPermission, roleDefinitions } from '../../lib/workspace.js'

function CustomFieldInputs({ definitions = [], values = {}, onChange }) {
  if (!definitions.length) return null
  const setField = (key, value) => onChange({ ...(values || {}), [key]: value })
  return <section className="custom-field-runtime"><strong>Configured fields</strong>{definitions.filter(field => field.visible !== false).map(field => <label key={field.key || field.name}>{field.label || field.key}<input type={field.type === 'number' ? 'number' : field.type === 'date' ? 'date' : field.type === 'datetime' ? 'datetime-local' : field.type === 'checkbox' ? 'checkbox' : 'text'} checked={field.type === 'checkbox' ? Boolean(values?.[field.key]) : undefined} value={field.type === 'checkbox' ? undefined : (values?.[field.key] ?? '')} onChange={e => setField(field.key, field.type === 'checkbox' ? e.target.checked : e.target.value)} required={Boolean(field.required)}/></label>)}</section>
}

export function EntityFormModal({ modal, data, user, onClose, onSave, onDelete }) {
  const type = modal?.type
  const record = modal?.record
  const [form, setForm] = useState({})
  const [error, setError] = useState('')
  useEffect(() => {
    if (!type) return
    const firstProject = data.projects[0]?.numericId || ''
    const firstPerson = data.people[0]?.id || user?.personId || ''
    const firstTeam = data.teams[0]?.id || ''
    const taskStatuses = workflowStateLabels(data.settings)
    const presets = {
      task: { title: record?.title || '', projectId: record?.projectId || firstProject, assigneeId: record?.assigneeId || user?.personId || firstPerson, priority: record?.priority || 'Medium', dueDate: record?.dueDate || data.today, status: record?.status || taskStatuses[0] || 'To do', type: record?.type || 'Development', blocked: Boolean(record?.blocked), customFields: record?.customFields || {} },
      project: { name: record?.name || '', code: record?.code || '', description: record?.description || '', teamId: record?.teamId || firstTeam, ownerId: record?.ownerId || user?.personId || firstPerson, color: record?.color || 'purple', status: record?.status || 'On track', deadline: record?.deadlineDate || data.today, customFields: record?.customFields || {} },
      person: { name: record?.name || '', email: record?.email || '', jobTitle: record?.jobTitle || record?.role || 'Contributor', teamId: record?.teamId || firstTeam, focus: record?.focus || 'Workspace priorities', capacity: record?.capacity ?? record?.load ?? 70, status: record?.status || 'On track', color: record?.color || 'purple', customFields: record?.customFields || {} },
      team: { name: record?.name || '', color: record?.color || 'purple', customFields: record?.customFields || {} },
      milestone: { name: record?.name || '', projectId: record?.projectId || record?.project?.numericId || firstProject, dueDate: record?.dueDate || data.today, status: record?.status || 'Upcoming', customFields: record?.customFields || {} },
      activity: { personId: record?.personId || user?.personId || firstPerson, yesterday: '', today: '', blocked: '', upcoming: '', status: 'Confirmed', customFields: record?.customFields || {} },
      alert: { title: record?.title || '', body: record?.body || '', type: record?.type || 'info', tone: record?.tone || 'blue', projectId: record?.projectId || '', taskId: record?.taskId || '', customFields: record?.customFields || {} },
      user: { name: record?.name || '', email: record?.email || '', password: '', role: record?.role || 'Viewer', personId: record?.personId || firstPerson, avatarColor: record?.avatarColor || 'purple', active: record?.active !== false }
    }
    setForm(presets[type] || {})
    setError('')
  }, [type, record?.numericId, record?.id])
  if (!type) return null
  const isEdit = Boolean(record?.numericId || record?.id)
  const savePermission = { task: 'manageTasks', project: 'manageProjects', person: 'managePeople', team: 'managePeople', milestone: 'manageProjects', activity: 'logActivity', alert: 'manageAlerts', user: 'manageUsers' }[type]
  const deletePermission = { task: 'manageTasks', project: 'manageProjects', person: 'managePeople', team: 'managePeople', milestone: 'manageProjects', activity: 'manageTasks', alert: 'manageAlerts', user: 'manageUsers' }[type]
  const canSaveRecord = actionVisible(data.settings, isEdit ? 'edit' : 'create') && hasPermission(user, savePermission)
  const canDeleteRecord = isEdit && actionVisible(data.settings, 'delete') && hasPermission(user, deletePermission)
  const taskStatuses = workflowStateLabels(data.settings)
  const roles = roleDefinitions(data.settings)
  const fieldDefs = customFieldDefinitions(data.settings, type)
  const set = (key, value) => setForm(current => ({ ...current, [key]: value }))
  const submit = async e => { e.preventDefault(); setError(''); if (!canSaveRecord) return; try { await onSave(type, record, form); onClose() } catch (err) { setError(err.message) } }
  const fields = () => {
    if (type === 'task') return <><label data-form-fields="title">Task title<input autoFocus value={form.title || ''} onChange={e => set('title', e.target.value)} required/></label><div className="form-row" data-form-fields="projectId,assigneeId"><label>Project<select value={form.projectId || ''} onChange={e => set('projectId', e.target.value)}>{data.projects.map(p => <option key={p.numericId} value={p.numericId}>{p.name}</option>)}</select></label><label>Owner<select value={form.assigneeId || ''} onChange={e => set('assigneeId', e.target.value)}>{data.people.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label></div><div className="form-row" data-form-fields="priority,dueDate"><label>Priority<select value={form.priority || 'Medium'} onChange={e => set('priority', e.target.value)}><option>High</option><option>Medium</option><option>Low</option></select></label><label>Due date<input type="date" value={form.dueDate || ''} onChange={e => set('dueDate', e.target.value)}/></label></div><div className="form-row" data-form-fields="status,type"><label>Status<select value={form.status || 'To do'} onChange={e => set('status', e.target.value)}>{taskStatuses.map(s => <option key={s}>{s}</option>)}</select></label><label>Type<select value={form.type || 'Development'} onChange={e => set('type', e.target.value)}><option>Development</option><option>Design</option><option>Testing</option><option>Documentation</option></select></label></div><label className="checkbox-label" data-form-fields="blocked"><input type="checkbox" checked={Boolean(form.blocked)} onChange={e => set('blocked', e.target.checked)}/> This task is blocked</label></>
    if (type === 'project') return <><div className="form-row" data-form-fields="name,code"><label>Project name<input autoFocus value={form.name || ''} onChange={e => set('name', e.target.value)} required/></label><label>Code<input value={form.code || ''} onChange={e => set('code', e.target.value.toUpperCase())} required/></label></div><label data-form-fields="description">Objective<textarea value={form.description || ''} onChange={e => set('description', e.target.value)} rows="3"/></label><div className="form-row" data-form-fields="teamId,ownerId"><label>Team<select value={form.teamId || ''} onChange={e => set('teamId', e.target.value)}>{data.teams.map(t => <option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label>Owner<select value={form.ownerId || ''} onChange={e => set('ownerId', e.target.value)}>{data.people.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label></div><div className="form-row" data-form-fields="status,deadline"><label>Status<select value={form.status || 'On track'} onChange={e => set('status', e.target.value)}><option>On track</option><option>At risk</option><option>Completed</option></select></label><label>Deadline<input type="date" value={form.deadline || ''} onChange={e => set('deadline', e.target.value)}/></label></div></>
    if (type === 'person') return <><div className="form-row" data-form-fields="name,email"><label>Full name<input autoFocus value={form.name || ''} onChange={e => set('name', e.target.value)} required/></label><label>Email<input type="email" value={form.email || ''} onChange={e => set('email', e.target.value)} required/></label></div><div className="form-row" data-form-fields="jobTitle,teamId"><label>Job title<input value={form.jobTitle || ''} onChange={e => set('jobTitle', e.target.value)}/></label><label>Team<select value={form.teamId || ''} onChange={e => set('teamId', e.target.value)}>{data.teams.map(t => <option key={t.id} value={t.id}>{t.name}</option>)}</select></label></div><label data-form-fields="focus">Current focus<input value={form.focus || ''} onChange={e => set('focus', e.target.value)}/></label><div className="form-row" data-form-fields="capacity,status"><label>Capacity<input type="number" min="0" max="100" value={form.capacity ?? 70} onChange={e => set('capacity', e.target.value)}/></label><label>Status<select value={form.status || 'On track'} onChange={e => set('status', e.target.value)}><option>On track</option><option>Needs attention</option></select></label></div></>
    if (type === 'team') return <><label data-form-fields="name">Team name<input autoFocus value={form.name || ''} onChange={e => set('name', e.target.value)} required/></label><label data-form-fields="color">Color<select value={form.color || 'purple'} onChange={e => set('color', e.target.value)}><option>purple</option><option>blue</option><option>orange</option><option>green</option><option>teal</option></select></label></>
    if (type === 'milestone') return <><label data-form-fields="name">Milestone name<input autoFocus value={form.name || ''} onChange={e => set('name', e.target.value)} required/></label><label data-form-fields="projectId">Project<select value={form.projectId || ''} onChange={e => set('projectId', e.target.value)}>{data.projects.map(p => <option key={p.numericId} value={p.numericId}>{p.name}</option>)}</select></label><div className="form-row" data-form-fields="dueDate,status"><label>Due date<input type="date" value={form.dueDate || ''} onChange={e => set('dueDate', e.target.value)}/></label><label>Status<select value={form.status || 'Upcoming'} onChange={e => set('status', e.target.value)}><option>Upcoming</option><option>At risk</option><option>Complete</option></select></label></div></>
    if (type === 'activity') return <><label data-form-fields="personId">Person<select value={form.personId || ''} onChange={e => set('personId', e.target.value)}>{data.people.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label data-form-fields="yesterday">Yesterday<textarea autoFocus value={form.yesterday || ''} onChange={e => set('yesterday', e.target.value)} rows="2"/></label><label data-form-fields="today">Today<textarea value={form.today || ''} onChange={e => set('today', e.target.value)} rows="2"/></label><label data-form-fields="blocked">Blocked<textarea value={form.blocked || ''} onChange={e => set('blocked', e.target.value)} rows="2"/></label><label data-form-fields="upcoming">Upcoming<textarea value={form.upcoming || ''} onChange={e => set('upcoming', e.target.value)} rows="2"/></label></>
    if (type === 'user') return <><div className="form-row" data-form-fields="name,email"><label>Full name<input autoFocus value={form.name || ''} onChange={e => set('name', e.target.value)} required/></label><label>Email<input type="email" value={form.email || ''} onChange={e => set('email', e.target.value)} required/></label></div><div className="form-row" data-form-fields="role,personId"><label>Role<select value={form.role || 'Viewer'} onChange={e => set('role', e.target.value)}>{Object.keys(roles).map(role => <option key={role}>{role}</option>)}</select></label><label>Linked person<select value={form.personId || ''} onChange={e => set('personId', e.target.value)}>{data.people.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label></div><label data-form-fields="password">{record ? 'New password (optional)' : 'Password'}<input type="password" value={form.password || ''} onChange={e => set('password', e.target.value)} minLength={record ? undefined : 8} required={!record}/></label><div className="form-row" data-form-fields="avatarColor,active"><label>Avatar color<select value={form.avatarColor || 'purple'} onChange={e => set('avatarColor', e.target.value)}><option>purple</option><option>blue</option><option>orange</option><option>green</option><option>pink</option><option>teal</option></select></label><label className="checkbox-label"><input type="checkbox" checked={form.active !== false} onChange={e => set('active', e.target.checked)}/> Account active</label></div><div className="settings-note" data-form-fields="role"><Icon name="check" size={15}/><span>{roles[form.role || 'Viewer']?.summary || roles[form.role || 'Viewer']?.description}</span></div></>
    return <><label data-form-fields="title">Alert title<input autoFocus value={form.title || ''} onChange={e => set('title', e.target.value)} required/></label><label data-form-fields="body">Details<textarea value={form.body || ''} onChange={e => set('body', e.target.value)} rows="3"/></label><div className="form-row" data-form-fields="type,projectId"><label>Type<select value={form.type || 'info'} onChange={e => set('type', e.target.value)}><option value="info">Info</option><option value="deadline">Deadline</option><option value="blocker">Blocker</option><option value="risk">Risk</option></select></label><label>Project<select value={form.projectId || ''} onChange={e => set('projectId', e.target.value)}><option value="">Workspace</option>{data.projects.map(p => <option key={p.numericId} value={p.numericId}>{p.name}</option>)}</select></label></div></>
  }
  const formSurface = { task: 'tasks', project: 'projects', person: 'people', user: 'users', activity: 'activity', alert: 'alerts', team: 'teams', milestone: 'milestones' }[type]
  const orderedFields = () => {
    const rendered = fields()
    const children = React.Children.toArray(React.isValidElement(rendered) && rendered.type === React.Fragment ? rendered.props.children : rendered)
    const configured = data.settings?.interface?.formLayouts?.[formSurface]
    if (!Array.isArray(configured) || !configured.length) return children
    const order = new Map(configured.map((key, index) => [String(key), index]))
    return children.map((child, index) => {
      const fieldKeys = String(child.props?.['data-form-fields'] || '').split(',').filter(Boolean)
      const ranks = fieldKeys.map(key => order.get(key)).filter(rank => rank !== undefined)
      return { child, index, rank: ranks.length ? Math.min(...ranks) : configured.length + index }
    }).sort((a, b) => a.rank - b.rank || a.index - b.index).map(item => item.child)
  }
  const title = `${isEdit ? 'Edit' : type === 'activity' ? 'Log' : 'Create'} ${type}`
  return <div className="modal-backdrop" onMouseDown={e => e.target === e.currentTarget && onClose()}><form className="modal" onSubmit={submit}><div className="modal-head"><div><span className="eyebrow"><span className="eyebrow-dot"/> Atlas record</span><h2>{title}</h2><p>Changes are saved to the local unified store immediately.</p></div><button type="button" className="icon-button" onClick={onClose}><Icon name="close" size={17}/></button></div><div className="form-fields">{orderedFields()}<CustomFieldInputs definitions={fieldDefs} values={form.customFields || {}} onChange={value => set('customFields', value)}/>{error && <div className="form-error"><Icon name="warning" size={15}/>{error}</div>}</div><div className="modal-foot">{canDeleteRecord && onDelete && <button type="button" className="secondary-button danger-button" onClick={() => onDelete(type, record)}>Delete</button>}<span/><button type="button" className="secondary-button" onClick={onClose}>Cancel</button><button className="primary-button" disabled={!canSaveRecord}>Save <Icon name="arrow" size={14}/></button></div></form></div>
}
